#!/bin/bash
###
###
#SBATCH --time=00:30:00
##SBATCH --ntasks=1
#SBATCH --ntasks-per-node=2
##SBATCH --ntasks-per-gpu=1
#SBATCH --tasks=1
#SBATCH --gres=gpu:2
#SBATCH --job-name=radial
#SBATCH --output=radial_00001.o%j
#SBATCH -p gpu # queue (partition) -- defq, eduq, gpuq, shortq

module load slurm
module load cuda10.0

# Execute the program
#for N in 1 2 4 8 16
#do
mpirun  ./radial_cuda 
#done

status=$?
if [ $status -ne 0 ]; then
    exit $status
fi