# -*- Makefile -*-

# ----------------------------------
# Main ForestClaw source code
# ----------------------------------
include src/Makefile.am

# ----------------------------------
# Solver libraries
# ----------------------------------
include src/solvers/amr_waveprop/Makefile.am

# ----------------------------------
# Applications
# ----------------------------------
include applications/dummy/Makefile.am
include applications/advection/2d/swirl/Makefile.am
include applications/advection/2d/hemisphere/Makefile.am
