#! /bin/bash

UNPACK="$HOME/nosave/unpack"
PRBASE="$WORK/local/p4est"
WHERE="FAST"

#export CFLAGS="-Wall -wd310,593,869,981"
export CFLAGS="-Wall -xhost -opt-prefetch"
#export CPPFLAGS="-I$TACC_PAPI_INC"

#if test "$GOTOBLAS" = "STATIC" ; then
#  export LDFLAGS="-L$TACC_PAPI_LIB $CCGO_EXTRA_LDFLAGS"
#  export LIBS="-lpapi $TACC_GOTOBLAS_LIB/libgoto_lp64.a $CCGO_EXTRA_LIBS"
#else
#  export LDFLAGS="-L$TACC_PAPI_LIB -L$TACC_GOTOBLAS_LIB $CCGO_EXTRA_LDFLAGS"
#  export LIBS="-lpapi -lgoto_lp64 $CCGO_EXTRA_LIBS"
#fi
 
function bdie () {
	echo "$@"
	exit 1
}

TGZ="$1"; shift
if test ! -f "$TGZ" ; then
	bdie "File with p4est .tar.gz not found"
fi
if ! (echo "$TGZ" | grep -q 'p4est.*.tar.gz') ; then
	bdie "File mismatch"
fi
DIR=`echo "$TGZ" | sed 's/\(p4est.*\).tar.gz/\1/'`
DIR=`basename $DIR`
echo "Target directory: $DIR"
if test -d "$UNPACK/$DIR" ; then
	echo "Directory found"
else
	echo -n "Unpacking... "
	tar -xvz -f "$TGZ" -C "$UNPACK" >/dev/null
	echo "done"
fi
cd "$UNPACK/$DIR"
if test ! -f src/p4est.h ; then
	bdie "Header file missing"
fi
mkdir -p "$WHERE" && cd "$WHERE" || bdie "Error in mkdir or cd"
../configure \
	--prefix="$PRBASE/$DIR/$WHERE" \
	--without-blas --enable-mpi --enable-mpiio \
	"$@" || bdie "Error in configure"
make -C sc -j 16 || bdie "Error in make sc"
make -j 16 || bdie "Error in make p4est"
make -j 8 install || bdie "Error in make install"
echo "Successfully installed into $PRBASE/$DIR/$WHERE"
