#! /bin/bash

#SBATCH -J swrl               # Job name
#SBATCH -o swrl.%j.out        # Name of stdout output file (%j expands to jobId)
#SBATCH -e swrl.%j.err        # Name of stderr output file (%j expands to jobId)
#SBATCH --mail-user=burstedde@ins.uni-bonn.de
#SBATCH --mail-type=fail
#SBATCH --mail-type=end
#SBATCH -A TG-DPP130002
#SBATCH -p development        # Queue name
#SBATCH -t 00:20:00           # Run time (hh:mm:ss)
#SBATCH -N 5                  # Total number of nodes requested (16 cores/node)
#SBATCH -n 80                 # Total number of mpi tasks requested

BDIR="$WORK/local/forestclaw/swirl"
BEXE="$BDIR/swirl"
COMM="$BEXE -F $BDIR/fclaw2d_defaults.ini \
            -W $BDIR/fclaw2d_waveprop.ini \
            --prefix=$SCRATCH/forestclaw/$SLURM_JOB_NAME.$SLURM_JOB_ID \
            --vtkout=3 --maxlevel=7"

echo "Starting $COMM"
ibrun $COMM
