/*
Copyright (c) 2012-2025 Carsten Burstedde, Donna Calhoun, Scott Aiton
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "fclaw_clawpatch_gauges.h"
#include "fclaw_gauges.h"


#include <fclaw_clawpatch.h>
#include <fclaw_clawpatch_options.h>

#include <fclaw_options.h>
#include <fclaw_global.h>

#ifdef __cplusplus
extern "C"
{
#endif

#if 0
/* fix syntax highlighting */    
#endif

/*
    Five main functions are defined here.  These are called virtually from 
    functions defined in fclaw_gauges.c. 

        -- void gauges_read_data(...)
            -- Reads data from a "gauge.data" file. 

        -- void gauges_create_files(...)
            -- Creates gauge output files

        -- void gauges_normalize_coordinates(...)
            -- this is used to locate the gauge within a block.  This may 
               be replaced by a higher level "gauge_in_block" routine which can 
               be used for cubed-sphere and other non-Cartesian mappings. 

        -- void gauges_update(...)
            -- Update the gauge value.  This requires interpolation from the 
               mesh to the gauge point.        

        -- void gauges_print_buffer(...)
            -- Print out the gauge buffer to a gauge file.

    One additional function is the user defined "move" function.  
*/


void fclaw_clawpatch_gauges_read_data(fclaw_global_t *glob, 
                                      fclaw_gauge_t **gauges,
                                      int *num_gauges,
                                      int *dim)
{
/* Sample gauges.data file */
/*
########################################################
### DO NOT EDIT THIS FILE:  GENERATED AUTOMATICALLY ####
### To modify data, edit  'write_gauges.py'         ####
###                                                 ####
########################################################

2                    =: dimension           
39                   =: ngauges             
   1  1.0000000000e+03  5.0000000000e+02   0.000000e+00  1.000000e+10
   2  2.0000000000e+03  5.0000000000e+02   0.000000e+00  1.000000e+10
   3  3.0000000000e+03  5.0000000000e+02   0.000000e+00  1.000000e+10
   ....
 507  2.2000000000e+05  2.2000000000e+04   0.000000e+00  1.000000e+10
 508  2.4000000000e+05  2.2000000000e+04   0.000000e+00  1.000000e+10

0.0                  =: min_time_increment  

*/

    /* 
        This reads the input file.  Data in the input file is 
        currently given as : 

            id     x        y       t0      t1
            ----------------------------------

        where

           id : Gauge ID (pos. integer).  These can be any meaningful values
          x,y : (x,y) location of stationary gauge
        t0,t1 : Time interval over which to track the gauge. 

        An additional value indicates the time increment.  We assume that this 
        increment will be the same for all gauges. 

        This data is stored in the `fclaw_gauge_t` data struct.  A void* in that 
        struct is used to store data in `clawpatch_gauge_data_t'. 
    */


    /* USER: Maximum line length in gauges input file gauges.data */

    FILE *f_gauges_data = fopen("gauges.data","r");
    if (f_gauges_data == NULL)
    {
        fclaw_abortf("read_gauges_data : Could not open gauges.data file.\n");
    }

    int max_line_len = 200;  
    char *line = FCLAW_ALLOC(char,max_line_len);

    /* Read 5 lines of the header */
    for(int i = 0; i < 5; i++)
    {
        /* Read lines of each header file.  Assume 100 chars in each line */
        fgets(line, max_line_len, f_gauges_data);
        if (line[0] != '#')
        {
            fclaw_global_essentialf("\n\n");
            fclaw_global_essentialf("read_gauges_data : Error reading header.\n");
            exit(0);
        }
    }

    /* Read a blank line */
    fgets(line,max_line_len, f_gauges_data); 

    /* Input/output : Read dimension */
    fgets(line,max_line_len, f_gauges_data);
    *dim = strtod(line,NULL);
    int gauge_dim = *dim;

    /* Input/output : Read number of gauges */
    fgets(line,max_line_len, f_gauges_data);
    *num_gauges = strtod(line,NULL);

    if (*num_gauges == 0)
    {
        *gauges = NULL;
    }
    else
    {
        /* Allocate temporary memory for gauges */
        fclaw_gauges_allocate(glob,*num_gauges,gauges);
        fclaw_gauge_t *g = *gauges;

        int *num = FCLAW_ALLOC(int,   *num_gauges);
        double *x0  = FCLAW_ALLOC(double,*num_gauges);
        double *y0  = FCLAW_ALLOC(double,*num_gauges);
        double *z0  = FCLAW_ALLOC(double,*num_gauges);
        double *t1  = FCLAW_ALLOC(double,*num_gauges);
        double *t2  = FCLAW_ALLOC(double,*num_gauges);
        double *min_time_increment = FCLAW_ALLOC(double,*num_gauges);

        /* Read gauge info for each gauge */
        char *next;  
        for(int i = 0; i < *num_gauges; i++)
        {                        
            fgets(line,max_line_len, f_gauges_data);
            num[i] = strtod(line,&next);
            x0[i] = strtod(next,&next);
            y0[i] = strtod(next,&next);
            z0[i] = (gauge_dim == 2) ? 0 : strtod(next,&next);
            t1[i] = strtod(next,&next);
            t2[i] = strtod(next,NULL);
        }

        /* Skip one line to get to min_time_increment */
        fgets(line,max_line_len,f_gauges_data);  

        /* Read minimum time increment */
        fgets(line,max_line_len,f_gauges_data);
        double min_inc = strtod(line,&next);
        /* Assume constant minimum time increment for all gauges */
        for(int i = 0; i < *num_gauges; i++)
        {
            min_time_increment[i] = min_inc; // strtod(next,&next);
        }

        /* Final step : Set gauge data */
        for(int i = 0; i < *num_gauges; i++)
        {
            /* Both (x0,y0,z0) and (xc,yc,zc) set to same values here */
            fclaw_gauges_set_data(glob,&g[i],num[i],gauge_dim,
                                 x0[i],y0[i],z0[i],x0[i],y0[i],z0[i],
                                 t1[i],t2[i],
                                 min_time_increment[i]);
        }

        FCLAW_FREE(num);
        FCLAW_FREE(x0);
        FCLAW_FREE(y0);
        FCLAW_FREE(z0);
        FCLAW_FREE(t1);
        FCLAW_FREE(t2);
        FCLAW_FREE(min_time_increment);

    }   /* End of num_gauges > 0 loop */

    /* Finish up */
    fclose(f_gauges_data);    
    FCLAW_FREE(line);
}

/* This function can be virtualized so the user can specify their 
   gauge output */

/* This has some clawpatch specific info (labels, for example) */
void fclaw_clawpatch_gauges_create_files(fclaw_global_t *glob, 
                                         fclaw_gauge_t *gauges,
                                         int num_gauges)
{

    /* -----------------------------------------------------
    Open output gauge files and add header information
    ----------------------------------------------------- */
    char filename[15];    /* gaugexxxxx.txt  + EOL */

    for (int i = 0; i < num_gauges; i++)
    {
        int num, dim;
        double xc,yc,zc, t1,t2;
        double x0, y0, z0;
        fclaw_gauges_get_data(glob,&gauges[i],&num, &dim, &x0, &y0, &z0,
                             &xc, &yc, &zc, &t1, &t2);

        sprintf(filename,"gauge%05d.txt",num);
        FILE *fp = fopen(filename, "w");
        if (dim == 2)
            fprintf(fp, "# gauge_id= %5d location=( %17.10e %17.10e )\n",
                    num, x0, y0);
        else if (dim == 3)
            fprintf(fp, "# gauge_id= %5d location=( %17.10e %17.10e %17.10e)\n",
                    num, x0, y0,z0);
        fprintf(fp, "# Columns: level x, y, z, time q0   q1   q2 .... aux0  aux1  aux 2...\n");
        fclose(fp);
    }
}

void fclaw_clawpatch_gauges_normalize_coordinates(fclaw_global_t *glob, 
                                                 fclaw_block_t *block,
                                                 int blockno, 
                                                 fclaw_gauge_t *g,
                                                 double *xc, double *yc,double *zc)
{
    /*  
       Map gauge to normalized coordinates in a global [0,1]x[0,1]  domain.

       Gauge coordinates (g->xc,g->yc) are whatever the user supplied above 

       Return normalized (xc,yc) coordinates for gauge.
    */

    fclaw_options_t *fclaw_opt = fclaw_get_options(glob);
    double ax = fclaw_opt->ax;
    double bx = fclaw_opt->bx;
    double ay = fclaw_opt->ay;
    double by = fclaw_opt->by;

    /* Map global gauge to global [0,1]x[0,1] space */
    *xc = (g->xc - ax)/(bx-ax);
    *yc = (g->yc - ay)/(by-ay);

    if (g->dim == 2)
    {        
        *zc = 0;
    }
    else if (g->dim == 3)
    {
        double az = fclaw_opt->az;
        double bz = fclaw_opt->bz;
        *zc = (g->zc - az)/(bz-az);
    }
}

/* Define user gauges - these store user data needed by each gauge */
static
void fclaw_clawpatch_gauges_allocate(fclaw_global_t *glob, 
                                     int meqn, int maux,
                                     fclaw_clawpatch_gauge_data_t **guser)
{
    *guser = FCLAW_ALLOC(fclaw_clawpatch_gauge_data_t,1);

    (*guser)->qvar = FCLAW_ALLOC(double,meqn);
    (*guser)->avar = FCLAW_ALLOC(double,maux);
}

static
void fclaw_clawpatch_gauges_deallocate(fclaw_global_t *glob,
                                       fclaw_clawpatch_gauge_data_t **guser)
{
    FCLAW_FREE((*guser)->qvar);
    FCLAW_FREE((*guser)->avar);
    FCLAW_FREE(*guser);
    *guser = NULL;
}



/* Interpolate patch data to gauge */
void fclaw_clawpatch_gauges_update(fclaw_global_t* glob, 
                                   fclaw_block_t* block,
                                   fclaw_patch_t* patch, 
                                   int blockno, int patchno,
                                   double tcurr, fclaw_gauge_t *g)
{
    /* Get basic gauge info : (id, xc, yc, t1, t2) */
    int num, dim;
    double xc,yc, zc, t1, t2;
    double x0, y0, z0;
    fclaw_gauges_get_data(glob,g,&num, &dim, &x0, &y0, &z0, 
                          &xc, &yc, &zc, &t1, &t2);

    /* Retrieve patch data */
    int meqn;
    double *q;
    fclaw_clawpatch_soln_data(glob,patch,&q,&meqn);

    int maux;
    double *aux;
    fclaw_clawpatch_aux_data(glob,patch,&aux,&maux);


    fclaw_clawpatch_vtable_t* clawpatch_vt = fclaw_clawpatch_vt(glob);
    double qvar[meqn], avar[maux];  /* q[meqn] */
    if (dim == 2)
    {
        int mx, my, mbc;
        double xlower,ylower,dx,dy;
        fclaw_clawpatch_2d_grid_data(glob,patch,&mx,&my,&mbc,
                                     &xlower,&ylower,&dx,&dy);

        /* Check that gauge is in current patch.  */
        if (!(xc >= xlower && xc <= xlower + mx*dx))
        {
            printf("xc : update\n");
            printf("num = %d\n",num);
            printf("xc = %20.16f; yc = %20.16f\n",xc,yc);
            printf("xlower = %20.16f;  ylower = %20.16f\n",xlower,ylower);
            printf("xupper = %20.16f;  yupper = %20.16f\n",xlower+mx*dx,ylower+my*dy);
            printf("\n\n");
        }

        if (!(yc >= ylower && yc <= ylower + my*dy))
        {
            printf("yc : update\n");
            printf("num = %d\n",num);
            printf("xc = %20.16f; yc = %20.16f\n",xc,yc);
            printf("xlower = %20.16f;  ylower = %20.16f\n",xlower,ylower);
            printf("xupper = %20.16f;  yupper = %20.16f\n",xlower+mx*dx,ylower+my*dy);
            printf("\n\n");
        }

#if 1
        FCLAW_ASSERT(xc >= xlower && xc <= xlower + mx*dx);
        FCLAW_ASSERT(yc >= ylower && yc <= ylower + my*dy);
#endif

        /* Interpolate q and aux variables to gauge location */
        clawpatch_vt->d2->fort_gauge_update(&num, &mx,&my,&mbc,&meqn,
                                            &xlower,&ylower,
                                            &dx,&dy,q,&maux,aux,&xc,&yc,
                                            qvar,avar);
    }
    else if (dim == 3)
    {
        int mx, my, mz,mbc;
        double xlower,ylower,zlower,dx,dy,dz;
        fclaw_clawpatch_3d_grid_data(glob,patch,&mx,&my,&mz,&mbc,
                                     &xlower,&ylower,&zlower,
                                     &dx,&dy,&dz);

        /* Check that gauge is in current patch */
        FCLAW_ASSERT(xc >= xlower && xc <= xlower + mx*dx);
        FCLAW_ASSERT(yc >= ylower && yc <= ylower + my*dy);
        FCLAW_ASSERT(zc >= zlower && zc <= zlower + mz*dz);

        /* Interpolate q and aux variables to gauge location */
        clawpatch_vt->d3->fort_gauge_update(&num, &mx,&my,&mz,&mbc,&meqn,
                                            &xlower,&ylower,&zlower,
                                            &dx,&dy,&dz,
                                            q,&maux,aux,&xc,&yc,&zc,
                                            qvar,avar);
    }

    /* 
        USER : Store qvar, avar and anything else into the 
        "fclaw_clawpatch_gauge_data_t" that is needed when 
        writing out gauges.  
    */

    fclaw_clawpatch_gauge_data_t *guser;
    fclaw_clawpatch_gauges_allocate(glob,meqn,maux,&guser);

    guser->level = patch->level;
    guser->tcurr = tcurr;

    guser->meqn = meqn;  /* Needed for printing the buffers */
    guser->maux = maux; 

    guser->xc = xc;
    guser->yc = yc;
    guser->zc = zc;

    /* USER : Store state values */
    for(int m = 0; m < meqn; m++)
    {
        guser->qvar[m] = qvar[m];
    }

    /* USER : Store aux values */
    for(int m = 0; m < maux; m++)
    {
        guser->avar[m] = avar[m];       
    }

    /* Store pointer  to guser in buffer for g for printing later */
    fclaw_gauges_set_buffer_entry(glob,g,guser);
}

/* Interpolate patch data to gauge */
void fclaw_clawpatch_gauges_move_local(fclaw_global_t* glob, 
                                       fclaw_block_t* block,
                                       fclaw_patch_t* patch, 
                                       int blockno, int patchno,
                                       double t, double dt, 
                                       fclaw_gauge_t *g)
{
    /* Get basic gauge info : (id, xc, yc, t1, t2) */
    int num, dim;
    double xc,yc, zc, t1, t2;
    double x0, y0, z0;
    fclaw_gauges_get_data(glob,g,&num, &dim, &x0, &y0, &z0, 
                          &xc, &yc, &zc, &t1, &t2);

    /* Retrieve patch data */
    int meqn;
    double *q;
    fclaw_clawpatch_soln_data(glob,patch,&q,&meqn);

    int maux;
    double *aux;
    fclaw_clawpatch_aux_data(glob,patch,&aux,&maux);

    fclaw_clawpatch_vtable_t* clawpatch_vt = fclaw_clawpatch_vt(glob);
    double xc_new, yc_new, zc_new;
    if (dim == 2)
    {
        int mx, my, mbc;
        double xlower,ylower,dx,dy;
        fclaw_clawpatch_2d_grid_data(glob,patch,&mx,&my,&mbc,
                                     &xlower,&ylower,&dx,&dy);

        if (!(xc >= xlower && xc <= xlower + mx*dx))
        {
            printf("xc : move local\n");
            printf("num = %d\n",num);

            printf("xc = %20.16f; yc = %20.16f\n",xc,yc);
            printf("xlower = %20.16f;  ylower = %20.16f\n",xlower,ylower);
            printf("xupper = %20.16f;  yupper = %20.16f\n",xlower+mx*dx,ylower+my*dy);
            printf("\n\n");
        }

        if (!(yc >= ylower && yc <= ylower + my*dy))
        {
            printf("yc : move local\n");
            printf("num = %d\n",num);
            printf("xc = %20.16f; yc = %20.16f\n",xc,yc);
            printf("xlower = %20.16f;  ylower = %20.16f\n",xlower,ylower);
            printf("xupper = %20.16f;  yupper = %20.16f\n",xlower+mx*dx,ylower+my*dy);
            printf("\n\n");
        }
#if 1
        /* Check that gauge is in current patch.  */
        FCLAW_ASSERT(xc >= xlower && xc <= xlower + mx*dx);
        FCLAW_ASSERT(yc >= ylower && yc <= ylower + my*dy);
#endif        




        /* Interpolate q and aux variables to gauge location */
        clawpatch_vt->d2->fort_gauge_move_local(&num, &mx,&my,&mbc,&meqn,
                                                &xlower,&ylower,
                                                &dx,&dy,q,&maux,aux,&xc,&yc,
                                                &t, &dt,
                                                &xc_new, &yc_new);

        /* Assume that in 2d, the z position does not move */
        zc_new = zc;
    }
    else if (dim == 3)
    {
        int mx, my, mz,mbc;
        double xlower,ylower,zlower,dx,dy,dz;
        fclaw_clawpatch_3d_grid_data(glob,patch,&mx,&my,&mz,&mbc,
                                     &xlower,&ylower,&zlower,
                                     &dx,&dy,&dz);

        /* Check that gauge is in current patch */
        FCLAW_ASSERT(xc >= xlower && xc <= xlower + mx*dx);
        FCLAW_ASSERT(yc >= ylower && yc <= ylower + my*dy);
        FCLAW_ASSERT(zc >= zlower && zc <= zlower + mz*dz);

        /* Interpolate q and aux variables to gauge location */
        clawpatch_vt->d3->fort_gauge_move_local(&num, &mx,&my,&mz,&mbc,&meqn,
                                                &xlower,&ylower,&zlower,
                                                &dx,&dy,&dz,
                                                q,&maux,aux,&xc,&yc,&zc,
                                                &t, &dt,
                                                &xc_new,&yc_new,&zc_new);
    }
    fclaw_gauges_set_position(glob, g, xc_new, yc_new, zc_new);
}


void fclaw_clawpatch_gauges_print(fclaw_global_t *glob, 
                                  fclaw_gauge_t *gauge) 
{


    /* This assumes on buffers be organized as an array; entries
       start at 0 and end with kmax-1 */
    int kmax;
    fclaw_clawpatch_gauge_data_t **gauge_buffer;
    fclaw_gauges_get_buffer(glob,gauge,&kmax,(void***) &gauge_buffer);

    int id = fclaw_gauges_get_id(glob,gauge);
    char filename[15];  /* gaugexxxxx.txt + EOL character */
    sprintf(filename,"gauge%05d.txt",id);

    FILE *fp = fopen(filename, "a");
    for(int k = 0; k < kmax; k++)
    {
        fclaw_clawpatch_gauge_data_t *guser = gauge_buffer[k];

        /* USER : Specify formatting here */
        fprintf(fp, "%5d %24.16f %24.16f %24.16f "\
                "%12.4e",guser->level, 
                guser->xc, guser->yc, guser->zc,
                guser->tcurr);
        int meqn = guser->meqn;
        for(int mq = 0; mq < meqn; mq++)
        {
            fprintf(fp,"%24.16e",guser->qvar[mq]);
        }

        int maux = guser->maux;
        for(int m = 0; m < maux; m++)
        {
            fprintf(fp,"%24.16e",guser->avar[m]);
        }
        fprintf(fp,"\n");

        fclaw_clawpatch_gauges_deallocate(glob,&guser);
    }
    fclose(fp);
}

#ifdef __cplusplus
}
#endif

