#!/usr/bin/env bash

../forestclaw/configure \
    --enable-mpi \
    --disable-shared \
    --enable-static \
    --without-blas \
    LDFLAGS="-L/usr/local/zlib/v1.2.7/lib -lz" \
    LIBS="-L/usr/local/zlib/v1.2.7/lib -lz" \
    CC=mpixlc_r \
    CXX=mpixlcxx_r  \
    F77=mpixlf77_r \
    FC=mpixlf90_r \
    CFLAGS="-O2 -qstrict -qarch=qp -qtune=qp -qnostaticlink -I/usr/local/zlib/include" \
    CXXFLAGS="-O2 -qstrict -qarch=qp -qtune=qp -qnostaticlink -I/usr/local/zlib/include" \
    FFLAGS="-O2 -qstrict -qarch=qp -qtune=qp -qnosave "

#     --no-recursion \
#     --with-p4est=/Users/calhoun/projects/ForestClaw/code/p4est-build-mpi/local \
#     --with-sc=/Users/calhoun/projects/ForestClaw/code/p4est-build-mpi/local
