/*
Copyright (c) 2012 Carsten Burstedde, Donna Calhoun
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "fc2d_geoclaw_gauges_default.h"

#include "fc2d_geoclaw_gauges.h"

#include "fc2d_geoclaw_options.h"

#include <fclaw2d_clawpatch.h>
#include <fclaw2d_clawpatch_options.h>

#include <fclaw2d_global.h>

#ifdef __cplusplus
extern "C"
{
#if 0
}
#endif
#endif


void read_gauges_data(fclaw2d_global_t *glob, 
                      geoclaw_gauge_t **gauges, 
                      int *num)
{
    /* Idea is that we may only need to change this file when updating to newer
       geoclaw code */
/* Sample gauges.data file */
/*
########################################################
### DO NOT EDIT THIS FILE:  GENERATED AUTOMATICALLY ####
### To modify data, edit  setrun.py                 ####
###    and then "make .data"                        ####
########################################################

18                   =: ngauges             
   1   8.6001000000e+01   1.0000000000e-03   0.000000e+00   1.000000e+10
   2   8.6876000000e+01   1.0000000000e-03   0.000000e+00   1.000000e+10
   3   8.7751000000e+01   1.0000000000e-03   0.000000e+00   1.000000e+10
   ....
*/

    FILE *f_gauges_data;
    int max_line_len = 200;  /* Maximum line length in file  gauges.data */
    char *line, *next;  
    int i;

    line = FCLAW_ALLOC(char,max_line_len);

    f_gauges_data = fopen("gauges.data","r");

    /* Read header */
    for(i = 0; i < 5; i++)
    {
        /* Read lines of each header file.  Assume 100 chars in each line */
        fgets(line, max_line_len, f_gauges_data);
        if (line[0] != '#')
        {
            fclaw_global_essentialf("\n\n");
            fclaw_global_essentialf("read_gauges_data : Error reading header.\n");
            exit(0);
        }
    }
    fgets(line,max_line_len, f_gauges_data); /* blank line */

    /* Read number of gauges */
    fgets(line,max_line_len, f_gauges_data);
    *num = strtod(line,NULL);

    *gauges = (geoclaw_gauge_t*) FCLAW_ALLOC(geoclaw_gauge_t,*num);
    geoclaw_gauge_t *g = *gauges;

    /* Read gauge info */
    for(i = 0; i < *num; i++)
    {
        fgets(line,max_line_len, f_gauges_data);
        g[i].num = strtod(line,&next);
        g[i].xc = strtod(next,&next);
        g[i].yc = strtod(next,&next);
        g[i].t1 = strtod(next,&next);
        g[i].t2 = strtod(next,NULL);
    }

    /* Skip a bunch of lines to get to min_time_increment */
    for(i = 0; i < 8; i++)
    {
        fgets(line,max_line_len,f_gauges_data);        
    }

    /* Read minimum time increment */
    fgets(line,max_line_len,f_gauges_data);
    g[0].min_time_increment = strtod(line,&next);
    for(i = 0; i < *num-1; i++)
    {
        g[i].min_time_increment = strtod(next,&next);
        fclaw_global_essentialf("%f\n",g[i].min_time_increment);
    }

    /* Finish up */
    fclose(f_gauges_data);    
    FCLAW_FREE(line);
}

/* This function can be virtualized so the user can specify their 
   gauge output */

void create_gauge_files(fclaw2d_global_t *glob, 
                        geoclaw_gauge_t *gauges, 
                        int num_gauges)
{
    const fclaw2d_clawpatch_options_t *clawpatch_opt = 
                            fclaw2d_clawpatch_get_options(glob);

    /* -----------------------------------------------------
    Open output gauge files and add header information
    ----------------------------------------------------- */
    char filename[15];    /* gaugexxxxx.txt  + EOL */
    FILE *fp;

    for (int i = 0; i < num_gauges; i++)
    {
        geoclaw_gauge_t g = gauges[i];
        sprintf(filename,"gauge%05d.txt",g.num);
        fp = fopen(filename, "w");
        fprintf(fp, "# gauge_id = %5d location = (%17.10e %17.10e) num_eqn = %2d\n",
                g.num, g.xc, g.yc, clawpatch_opt->meqn+1);

        fprintf(fp, "# Columns: level time h    hu    hv    eta\n");
        fclose(fp);
    }
}


#ifdef __cplusplus
#if 0
{
#endif
}
#endif

