/*
Copyright (c) 2012 Carsten Burstedde, Donna Calhoun
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "fc2d_geoclaw_gauges_default.h"

#include "fc2d_geoclaw_gauges.h"
#include "fc2d_geoclaw_fort.h"

#include "fc2d_geoclaw_options.h"

#include <fclaw2d_clawpatch.h>
#include <fclaw2d_clawpatch_options.h>

#include <fclaw2d_global.h>

#ifdef __cplusplus
extern "C"
{
#if 0
}
#endif
#endif

typedef struct geoclaw_user
{
    int level;
    double tcurr;
    double qvar[3];  /* Store h, hu, hv */
    double avar[1];  /* Store bathymetry */
} geoclaw_user_t;



void geoclaw_read_gauges_data_default(fclaw2d_global_t *glob, 
                                      fc2d_geoclaw_gauge_t **gauges, 
                                      int *num_gauges)
{
    /* Idea is that we may only need to change this file when updating to newer
       geoclaw code */
/* Sample gauges.data file */
/*
########################################################
### DO NOT EDIT THIS FILE:  GENERATED AUTOMATICALLY ####
### To modify data, edit  setrun.py                 ####
###    and then "make .data"                        ####
########################################################

18                   =: ngauges             
   1   8.6001000000e+01   1.0000000000e-03   0.000000e+00   1.000000e+10
   2   8.6876000000e+01   1.0000000000e-03   0.000000e+00   1.000000e+10
   3   8.7751000000e+01   1.0000000000e-03   0.000000e+00   1.000000e+10
   ....
*/

    FILE *f_gauges_data;
    int max_line_len = 200;  /* Maximum line length in file  gauges.data */
    char *line, *next;  
    int i;

    line = FCLAW_ALLOC(char,max_line_len);

    f_gauges_data = fopen("gauges.data","r");

    /* Read header */
    for(i = 0; i < 5; i++)
    {
        /* Read lines of each header file.  Assume 100 chars in each line */
        fgets(line, max_line_len, f_gauges_data);
        if (line[0] != '#')
        {
            fclaw_global_essentialf("\n\n");
            fclaw_global_essentialf("read_gauges_data : Error reading header.\n");
            exit(0);
        }
    }
    /* blank line */
    fgets(line,max_line_len, f_gauges_data); 

    /* Read number of gauges */
    fgets(line,max_line_len, f_gauges_data);
    *num_gauges = strtod(line,NULL);

    if (*num_gauges == 0)
    {
        *gauges = NULL;
    }
    else
    {
        *gauges = (fc2d_geoclaw_gauge_t*) FCLAW_ALLOC(fc2d_geoclaw_gauge_t,*num_gauges);
        fc2d_geoclaw_gauge_t *g = *gauges;

        /* Read gauge info */
        for(i = 0; i < *num_gauges; i++)
        {
            fgets(line,max_line_len, f_gauges_data);
            g[i].num = strtod(line,&next);
            g[i].xc = strtod(next,&next);
            g[i].yc = strtod(next,&next);
            g[i].t1 = strtod(next,&next);
            g[i].t2 = strtod(next,NULL);
        }

        /* Skip a bunch of lines to get to min_time_increment */
        for(i = 0; i < 8; i++)
        {
            fgets(line,max_line_len,f_gauges_data);        
        }

        /* Read minimum time increment */
        fgets(line,max_line_len,f_gauges_data);
        g[0].min_time_increment = strtod(line,&next);
        for(i = 1; i < *num_gauges; i++)
        {
            g[i].min_time_increment = strtod(next,&next);
        }
    }   /* End of num_gauges > 0 loop */

    /* Finish up */
    fclose(f_gauges_data);    
    FCLAW_FREE(line);
}

/* This function can be virtualized so the user can specify their 
   gauge output */

void geoclaw_create_gauge_files_default(fclaw2d_global_t *glob, 
                                        fc2d_geoclaw_gauge_t *gauges, 
                                        int num_gauges)
{
    const fclaw2d_clawpatch_options_t *clawpatch_opt = 
                            fclaw2d_clawpatch_get_options(glob);

    /* -----------------------------------------------------
    Open output gauge files and add header information
    ----------------------------------------------------- */
    char filename[15];    /* gaugexxxxx.txt  + EOL */
    FILE *fp;

    int num_eqns = clawpatch_opt->meqn+1;
    for (int i = 0; i < num_gauges; i++)
    {
        fc2d_geoclaw_gauge_t g = gauges[i];
        sprintf(filename,"gauge%05d.txt",g.num);
        fp = fopen(filename, "w");
        /* This must have exactly the spacing indicated below. 
           See line 99 of $CLAW/pyclaw/src/pyclaw/gauges.py */
        fprintf(fp, "# gauge_id= %5d location=( %17.10e %17.10e ) num_eqn= %2d\n",
                g.num, g.xc, g.yc, num_eqns);

        fprintf(fp, "# Columns: level time h    hu    hv    eta\n");
        fclose(fp);
    }
}

void geoclaw_gauge_update_default(fclaw2d_global_t* glob, fclaw2d_block_t* block,
                                  fclaw2d_patch_t* patch, int blockno, int patchno,
                                  double tcurr, fc2d_geoclaw_gauge_t *g)
{
    int mx,my,mbc,meqn,maux;
    double xlower,ylower,dx,dy;
    double *q, *aux;
    double qvar[3], avar[1];  /* q[meqn] */

    fclaw2d_clawpatch_grid_data(glob,patch,&mx,&my,&mbc,
                                &xlower,&ylower,&dx,&dy);

    FCLAW_ASSERT(g->xc >= xlower && g->xc <= xlower + mx*dx);
    FCLAW_ASSERT(g->yc >= ylower && g->yc <= ylower + my*dy);

    fclaw2d_clawpatch_soln_data(glob,patch,&q,&meqn);
    fclaw2d_clawpatch_aux_data(glob,patch,&aux,&maux);

    /* Interpolate q variables and aux variables (bathy only for now)
       to gauge location */
    FC2D_GEOCLAW_UPDATE_GAUGE(&mx,&my,&mbc,&meqn,&xlower,&ylower,
                              &dx,&dy,q,&maux,aux,&g->xc,&g->yc,
                              qvar,avar);
                
    /* Store qvar, avar in gauge buffers */
    geoclaw_store_gauge_vars_default(glob, patch->level, tcurr, qvar,avar,g); 
}


void geoclaw_store_gauge_vars_default(fclaw2d_global_t *glob,
                                      int level, double tcurr,
                                      double* qvar, double *avar, 
                                      fc2d_geoclaw_gauge_t *gauge)
{
    int meqn, k;
    int m;

    const fclaw2d_clawpatch_options_t *clawpatch_opt = 
                   fclaw2d_clawpatch_get_options(glob);

    k = gauge->buffer_index;
    meqn = clawpatch_opt->meqn;

    gauge->buffer[k] = FCLAW_ALLOC(geoclaw_user_t,1);
    geoclaw_user_t *g = (geoclaw_user_t*) gauge->buffer[k];
    g->level = level;
    g->tcurr = tcurr;
    for(m = 0; m < meqn; m++)
    {
        g->qvar[m] = qvar[m];
    }
    g->avar[0] = avar[0];   /* Just store bathymetry for now */
}


void geoclaw_print_gauges_default(fclaw2d_global_t *glob, 
                                  fc2d_geoclaw_gauge_t *gauge) 
{
    int k;

    char filename[15];  /* gaugexxxxx.txt + EOL character */
    FILE *fp;

    sprintf(filename,"gauge%05d.txt",gauge->num);
    fp = fopen(filename, "a");
    for(k = 0; k < gauge->buffer_index; k++)
    {
        geoclaw_user_t *g = (geoclaw_user_t*) &gauge->buffer[k];

        double eta = g->qvar[0] + g->avar[0];
        eta = abs(eta) < 1e-99 ? 0 : eta; /* For reading in Matlab */
        fprintf(fp, "%5d %15.7e %15.7e %15.7e %15.7e %15.7e\n",
                g->level,g->tcurr,g->qvar[0],g->qvar[1],
                g->qvar[2],eta);
        FCLAW_FREE(gauge->buffer[k]);
    }
    fclose(fp);
}

void geoclaw_gauge_destroy_default(fclaw2d_global_t *glob, fc2d_geoclaw_gauge_t *g)
{
    FCLAW_FREE(g->buffer);
}

#ifdef __cplusplus
#if 0
{
#endif
}
#endif

