/*
Copyright (c) 2012-2022 Carsten Burstedde, Donna Calhoun, Scott Aiton
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

//fclaw2d_clawpatch_conservation.h
#define fclaw2d_clawpatch_registers_t fclaw3dx_clawpatch_registers_t
#define fclaw2d_clawpatch_registers fclaw3dx_clawpatch_registers
#define fclaw2d_clawpatch_packmode fclaw3dx_clawpatch_packmode
#define fclaw2d_clawpatch_fort_time_sync_f2c_t fclaw3dx_clawpatch_fort_time_sync_f2c_t
#define fclaw2d_clawpatch_fort_time_sync_samesize_t fclaw3dx_clawpatch_fort_time_sync_samesize_t
#define fclaw2d_clawpatch_time_sync_new fclaw3dx_clawpatch_time_sync_new
#define fclaw2d_clawpatch_time_sync_delete fclaw3dx_clawpatch_time_sync_delete
#define fclaw2d_clawpatch_time_sync_setup fclaw3dx_clawpatch_time_sync_setup
#define fclaw2d_clawpatch_time_sync_f2c fclaw3dx_clawpatch_time_sync_f2c
#define fclaw2d_clawpatch_time_sync_samesize fclaw3dx_clawpatch_time_sync_samesize
#define fclaw2d_clawpatch_time_sync_reset fclaw3dx_clawpatch_time_sync_reset
#define fclaw2d_clawpatch_time_sync_pack_registers fclaw3dx_clawpatch_time_sync_pack_registers

//fclaw2d_clawpatch_fort.h
#define clawpatch_fort_copy_face_t fclaw3dx_clawpatch_fort_copy_face_t
#define clawpatch_fort_average_face_t fclaw3dx_clawpatch_fort_average_face_t
#define clawpatch_fort_interpolate_face_t fclaw3dx_clawpatch_fort_interpolate_face_t
#define clawpatch_fort_copy_corner_t fclaw3dx_clawpatch_fort_copy_corner_t
#define clawpatch_fort_average_corner_t fclaw3dx_clawpatch_fort_average_corner_t
#define clawpatch_fort_interpolate_corner_t fclaw3dx_clawpatch_fort_interpolate_corner_t
#define clawpatch_fort_tag4refinement_t fclaw3dx_clawpatch_fort_tag4refinement_t
#define clawpatch_fort_tag4coarsening_t fclaw3dx_clawpatch_fort_tag4coarsening_t
#define clawpatch_fort_exceeds_threshold_t fclaw3dx_clawpatch_fort_exceeds_threshold_t
#define clawpatch_fort_interpolate2fine_t fclaw3dx_clawpatch_fort_interpolate2fine_t
#define clawpatch_fort_average2coarse_t fclaw3dx_clawpatch_fort_average2coarse_t
#define clawpatch_fort_timeinterp_t fclaw3dx_clawpatch_fort_timeinterp_t
#define clawpatch_fort_local_ghost_pack_t fclaw3dx_clawpatch_fort_local_ghost_pack_t
#define clawpatch_fort_header_ascii_t fclaw3dx_clawpatch_fort_header_ascii_t
#define clawpatch_fort_output_ascii_t fclaw3dx_clawpatch_fort_output_ascii_t
#define clawpatch_fort_error_t fclaw3dx_clawpatch_fort_error_t
#define clawpatch_fort_conscheck_t fclaw3dx_clawpatch_fort_conscheck_t
//#define clawpatch_fort_area_t fclaw3dx_clawpatch_fort_area_t
#define clawpatch_fort_norm_t fclaw3dx_clawpatch_fort_norm_t
#define FCLAW2D_CLAWPATCH_GET_REFINEMENT_CRITERIA FCLAW3DX_CLAWPATCH_GET_REFINEMENT_CRITERIA
#define FCLAW2D_CLAWPATCH_EXCEEDS_THRESHOLD FCLAW3DX_CLAWPATCH_EXCEEDS_THRESHOLD

//fclaw2d_clawpatch_transform.h
#define fclaw2d_clawpatch_transform_init_data fclaw3dx_clawpatch_transform_init_data
#define fclaw2d_clawpatch_face_transformation fclaw3dx_clawpatch_face_transformation
#define fclaw2d_clawpatch_face_transformation_intra fclaw3dx_clawpatch_face_transformation_intra 
#define FCLAW2D_CLAWPATCH_TRANSFORM_FACE FCLAW3DX_CLAWPATCH_TRANSFORM_FACE
#define FCLAW2D_CLAWPATCH_TRANSFORM_FACE_HALF FCLAW3DX_CLAWPATCH_TRANSFORM_FACE_HALF
#define FCLAW2D_CLAWPATCH_TRANSFORM_CORNER FCLAW3DX_CLAWPATCH_TRANSFORM_CORNER
#define FCLAW2D_CLAWPATCH_TRANSFORM_CORNER_HALF FCLAW3DX_CLAWPATCH_TRANSFORM_CORNER_HALF

#if 0
#define fclaw2d_clawpatch_get_metric_patch fclaw3dx_clawpatch_get_metric_patch
#endif